### PR TITLE
cast-web-api global package

### PR DESCRIPTION
**Pull request by kevireilly**
This node script is a great candidate for a global package, so I added the ability and made some other small adjustments. If all seems well, you would need to [publish](https://docs.npmjs.com/getting-started/publishing-npm-packages) this module after merging in the changes to make it available for installation.

### CODE REVIEW

**Comment by vervallsweg** [comment]
Man you made my day. So awesome, I was trying to get this to work for some time now. Couldn't find any instruction how to do it, or get usable insight from other packages that install globally. That's why I just gave up.

Installing it globally was the [idea all along](https://community.smartthings.com/t/release-cast-web-0-2-chromecast-device-handler-smartapps/88038/253?u=vervallsweg) but as said never worked.

Thanks again, this looks really awesome, even with the version changed. Will merge it into release 0.3.

**Comment by vervallsweg** [comment]
Oh and does this really only work on node > 6.0.0? Or was this just your guess? Because I checked the dependencies down to 4.x and it works. Not sure how the global install would affect that.

**Comment by kevireilly** [comment]
@vervallsweg Aw shucks, I'm happy to have made your day. To be honest, your epic contribution of all this work made my day, so it was the least I could do. Sorry, I should have mentioned that I was more than willing to adjust the commit or explain anything before it got merged in (guess it isn't too late!). We can undo the commit to v0.3.0 and I can open another one with any arrangement or changes that you'd prefer.

I was getting some errors running the script when using node 5 via [nvm](https://github.com/creationix/nvm) due to ES6 use and I think [this](http://node.green/) table of support potentially backs that. I can test this again and provide the produced output on older versions.

When you use back ticks in bash, it will execute the command within and return the output. In this instance, the `which` command tells you where a binary is located on the filesystem so `which cast-web-api` will return the path to the node script to be ran by forever. I took this approach because there are a number of different paths that node and this global module can live.

Actually, the above may not work on Windows, but I wasn't able to test. Perhaps NPM can return a path to the global module instead -- will see if I can produce a more cross platform solution. I was also contemplating making this in to a desktop application via NW.js that could live as task bar item, drop down menus for configuration/output/[autolaunch](https://github.com/Teamwork/node-auto-launch) while providing the same basic functionality across platforms.

**Comment by kevireilly** [comment]
One more important bit of information: you can test these changes without publishing by doing `npm install -g ./` or any path to this module's root directory.

**Comment by vervallsweg** [comment]
Thanks a lot :) 

Good that you even checked the compatibly, I didn't even know such a table existed.

I'll try this on windows tomorrow. Windows support should be possible and is kind of a dealbreaker. Surprisingly many people use this on windows. Personally I don't find it that appealing to have like a full blown desktop computer going 24/7 if your router or literally anything else can run it. Anyway. Maybe we can learn from the [forever npm package](https://github.com/foreverjs/forever)? Theres runs on windows perfectly fine as a global installation.

The taskbar application is really appealing but if it worked as a global package first, that would already be awesome enough. Oh and yes, I did think about making it a proper cross platform daemon with autolaunch. However I'll upgrade it to a proper API before going fancy on the packaging.

And thanks for pointing out #62 and `npm install -g ./`, as said I'm not really experienced in npm and didn't have enough time to learn it from the ground up. 👍

**Comment by kevireilly** [comment]
My pleasure.

I re-verified on Node 4 and 5 and definitely a no go presently. I believe this is due to the mdn-js module's use of ES6 patterns that are not supported on <6 even with the `node --harmony` flag being passed:
```
$ node --harmony castWebApi.js 
.../cast-web-api/node_modules/mdns-js/lib/browser.js:4
const { EventEmitter } = require('events');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (.../cast-web-api/node_modules/mdns-js/index.js:14:40)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

Also worth noting that presently mdns-js 1.0.1 actually wants >= 8  😬 But seems to work fine (at least for me) on OSX with Node 6?
> npm WARN engine mdns-js@1.0.1: wanted: {"node":">= 8.0.0"} (current: {"node":"4.4.4","npm":"2.15.1"})

One way to handle this is to use [caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) and change the dependency from `"mdns-js": ">=0.5.3"` to `"mdns-js": "^0.5.3"` (or more recent desirable version) so <1.0.0 is installed. This may allow `engines.node` to drop back down to 4 and sorry I didn't assess this appropriately previously, I was pretty tired. Another option is to bump it up to 8, check the implementation for issues, and roll forward.

Windows support should not be undervalued indeed and if the case is that many people are using this on Windows, that infers that they're likely running this on a desktop computer 24/7. Totally agree that there is likely a decent percentage of people not doing that, perhaps even a majority, but those that aren't might appreciate it. Hard to say without data driving this. Consider this more of an option rather than the only way forward -- users could still install globally or even just clone and run on *nix or otherwise.

I love forever, I've used it a lot for personal and production use. The main problem I'm not being super explicit about is how to best handle the common problem of rebooting or loosing power and things not coming back online when the computer starts, regardless of platform. I couldn't get autolaunch to work properly, but perhaps that was because I was trying to do it programmatically in the global module as opposed to using the global install. Either way, it didn't seem super intuitive. 

The `crontab` approach as an example is one of many options for *nix which honestly isn't necessarily the best way, but it is an easy way. I'd probably use an upstart/init.d script for *nix (not sure if supported on OSX actually), but I was considering the potential end-user.

So, there is `npm root -g` which produces a path to the global module root directory like `/Users/username/.nvm/versions/node/v6.13.0/lib/node_modules` and it would be easy enough to append `/cast-web-api/bin/cast-web-api` to that when using `forever`. What I don't know how to do in Windows is something like back ticks so that we could do the *nix equivalent of
```
forever start `npm root -g`/cast-web-api/bin/cast-web-api
```

You did a great job on all of this. It pretty much just worked and that is awesome. Lots of moving parts yet it still "just works". Impressive :)

**Pull request merged**
