### PR TITLE
added in a method that uses google-tts for a more 'Google-y' voice

### PR DESCRIPTION
**Pull request by CultusMechanicus**
So this adds in the unofficial Google TTS api from npm. The voice is a much closer match for the standard Google Home voice.

### CODE REVIEW

**Comment by vervallsweg** [comment]
This looks really nice! Are you intending to use this in SmartThings?

**Comment by CultusMechanicus** [comment]
Yep, already using it. I've got the changes for the cast web DTH to use this as well. I'll set up a PR for that side too.

**Comment by CultusMechanicus** [comment]
DTH PR is up too. With both changes, you can use the  speak( text ) method on the DTH as a direct TTS.

**Comment by vervallsweg** [comment]
Sorry, I'm quite busy and working on v1.0.0 of the API. Your work looks really good, and multiple voices is something that a lot of people want.

I'm kind of split on that though:

1. Is this the job of the DTH to offer multiple TTS voices? Isn't this the job of ST or:
2. an external smartapp, like Big-Speaker?

If it is our job:

3. Should it be implemented in the DTH or API?
-> Because a lot of people find it very difficult to install the API I'd like to keep it as minimal as possible.

I really don't know the answer to this. Personally I don't think this is our job in the first place. But a lot of people want it, so why not. However I'd prefer making an external smartapp for that. I think it would benefit more people, since it's not just limited to cast-web. But: external smartapp is harder to automate with something like webCoRE.

I'd really like your opinion on this, since I don't really now which option is better.

Someone already implemented a bunch of TTS services for his own DTH in ST. I'll link that here later. Also check out the v1.0.0 branch or cast-web-api@beta on npm. v1 is rewritten from the ground up.

**Comment by CultusMechanicus** [comment]
Given that these changes are around the .speak() method that's required for the SmartThings (Speech Synthesis capability)[http://docs.smartthings.com/en/latest/capabilities-reference.html#speech-synthesis] I'd say it's absolutely supposed to be part of the DTH and/or any backing service. The entire point of speak() is that you just throw in a string and the device deals with everything else. 

In this case, given it's always going to be used with Google devices, it seems to make sense to set up the default voice to match the device's default voice (if it has one, Chromecasts don't, Homes obviously do).

Lastly, if the google-tts api was a simple post to a URL then it would be easy to add directly into the DTH and ship it off through .playAudioNotification(). Sadly it does Magic Stuff(tm) and needs to be sat in nodejs server. It doesn't actually add any extra install steps though, since it's in npm and can be pulled in through package.json. 

v1.0.0 looks great, I'll reserve a weekend to have a play around with it :)

**Comment by vervallsweg** [comment]
> The entire point of speak() is that you just throw in a string and the device deals with everything else.

True. Makes sense especially for webCoRE, etc.

> Lastly, if the google-tts api was a simple post to a URL then it would be easy to add directly into the DTH and ship it off through .playAudioNotification(). Sadly it does Magic Stuff(tm) and needs to be sat in nodejs server

I'm pretty sure I saw an open source ST implementation for Google TTS already. Will search for it. Since Google supports multiple voices afaik, it would make selection of the desired voice easier if it was in the DTH.

Will also create a feature poll for v.1 soon. This is definitely on the list 👍  

> v1.0.0 looks great, I'll reserve a weekend to have a play around with it :)

Thanks 🙂 If you're part of the ST forum, I have an instructions post on there on how to install v.1 and gather the feedback. Just pm me on there if you're interested.

**Comment by vervallsweg** [comment]
There you go, will look into this:

https://github.com/SmartThingsUle/DLNA-PLAYER/blob/master/Weather_Report.groovy

**Comment by CultusMechanicus** [comment]
The calls to translate_tts in Weather_Report fail because it's missing the "tk" parameter. Google added in a time sensitive key at some point in 2017. The npm module I found deals with this, but I don't think there's a way to move it over to the ST side. It should be possible to set the voice on the DTH side though. That way it shouldn't be any harder to install and configure than it is at the moment. 

Is v1.0.0 the recommended branch to do any future work against?

**Comment by vervallsweg** [comment]
Hey, just implemented the package you used in v1 of cast-web-api. Since v1 supports queueing, you can now also queue Google TTS messages with normal media.
It uses the standard [/playMedia](https://github.com/vervallsweg/cast-web-api/tree/v1.0.0#playmedia-http-post) command and with just an extra key 'googleTTS':'language-code' added to it. Uses title as the TTS text and subtitle as the receiver title.

You can install v1 through npm `cast-web-api@beta` or GitHub.
If theres anything missing from the implementation let me know :)

**Pull request closed without merging**
