### PR TITLE
Grab friendly name from anywhere in array

### PR DESCRIPTION
**Pull request by jg123**
The Vizio sound bar's fn lives in index 7. The code now searches for fn=
and uses that line for the friendly name instead of null. Also added
command for npm start and gitignored node_modules and npm-debug.log.

### CODE REVIEW

**Comment by jg123** [comment]
I removed the 0.0.0.0 setting.

**Comment by vervallsweg** [comment]
Thanks a lot, will be released in v0.2.4 soon. Will check on some other pr's/issues that I can maybe combined with this.

**Comment by vervallsweg** [comment]
Will be v0.3.0

**Comment by jg123** [comment]
👍

**Pull request merged**
